# Generated by Django 3.1.6 on 2021-04-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representant', models.CharField(max_length=20)),
                ('number_of_visitors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M', 'Mountain'), ('F', 'Freshwater'), ('W', 'Wetlands'), ('FO', 'Forest'), ('D', 'Desert'), ('S', 'Sea'), ('SA', 'Savannah'), ('J', 'Jungle')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSS', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=20)),
                ('classes', models.CharField(choices=[('M', 'Mammal'), ('R', 'Reptile'), ('B', 'Bird'), ('A', 'Amphibian')], max_length=1)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('life_expectancy', models.IntegerField()),
                ('alimentation', models.CharField(choices=[('C', 'Carnivorous'), ('H', 'Herbivorous'), ('O', 'Omnivorous'), ('F', 'Fruitarian'), ('I', 'Filter'), ('S', 'Scavenger'), ('I', 'Insectivorous'), ('P', 'Piscivorous')], max_length=2)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZooWeb.sector')),
            ],
        ),
    ]
