# Generated by Django 3.1.6 on 2021-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0003_auto_20210407_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=20),
        ),
    ]
