# Generated by Django 3.1.6 on 2021-04-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0004_auto_20210407_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='area_in_square_meters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='animals',
            field=models.ManyToManyField(to='ZooWeb.Animal'),
        ),
        migrations.AddField(
            model_name='worker',
            name='sectors',
            field=models.ManyToManyField(to='ZooWeb.Sector'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(choices=[('M', 'Mountain'), ('F', 'Freshwater'), ('W', 'Wetlands'), ('FO', 'Forest'), ('D', 'Desert'), ('S', 'Sea'), ('SA', 'Savannah'), ('J', 'Jungle')], max_length=2, unique=True),
        ),
        migrations.CreateModel(
            name='GuidedTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group_of_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZooWeb.groupofvisitor')),
                ('sector', models.ManyToManyField(to='ZooWeb.Sector')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZooWeb.worker')),
            ],
        ),
    ]
