# Generated by Django 3.1.6 on 2021-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0007_auto_20210407_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='height',
            new_name='height_in_centimeters',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='weight',
            new_name='weight_in_kilograms',
        ),
        migrations.AlterField(
            model_name='worker',
            name='NSS',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='animals',
            field=models.ManyToManyField(blank=True, to='ZooWeb.Animal'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='ZooWeb.Sector'),
        ),
    ]
