# Generated by Django 3.1.6 on 2021-05-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0014_remove_guidedtour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofvisitor',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
