# Generated by Django 3.1.6 on 2021-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0016_auto_20210505_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofvisitor',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='groupofvisitor',
            unique_together={('date', 'hour')},
        ),
    ]
