# Generated by Django 3.1.6 on 2021-05-13 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0019_auto_20210505_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofvisitor',
            name='city',
            field=models.CharField(default='Barcelona', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupofvisitor',
            name='country',
            field=models.CharField(default='Spain', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupofvisitor',
            name='phone',
            field=models.IntegerField(default='61234567', validators=[django.core.validators.MinValueValidator(600000000), django.core.validators.MaxValueValidator(799999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupofvisitor',
            name='region',
            field=models.CharField(default='Catalonia', max_length=120),
            preserve_default=False,
        ),
    ]
