# Generated by Django 3.1.6 on 2021-05-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0020_auto_20210513_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupofvisitor',
            old_name='city',
            new_name='user_city',
        ),
        migrations.RenameField(
            model_name='groupofvisitor',
            old_name='country',
            new_name='user_country',
        ),
        migrations.RenameField(
            model_name='groupofvisitor',
            old_name='phone',
            new_name='user_phone',
        ),
        migrations.RenameField(
            model_name='groupofvisitor',
            old_name='region',
            new_name='user_region',
        ),
    ]
