# Generated by Django 3.1.6 on 2021-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0002_auto_20210407_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='surname',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
