# Generated by Django 3.1.6 on 2021-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0002_auto_20210407_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='alimentation',
            field=models.CharField(choices=[('C', 'Carnivorous'), ('H', 'Herbivorous'), ('O', 'Omnivorous'), ('F', 'Fruitarian'), ('I', 'Filter'), ('S', 'Scavenger'), ('I', 'Insectivorous'), ('P', 'Piscivorous')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='life_expectancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='sector',
            field=models.CharField(choices=[('M', 'Mountain'), ('F', 'Freshwater'), ('W', 'Wetlands'), ('FO', 'Forest'), ('D', 'Desert'), ('S', 'Sea'), ('SA', 'Savannah'), ('J', 'Jungle')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='NSS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='classes',
            field=models.CharField(choices=[('M', 'Mammal'), ('R', 'Reptile'), ('B', 'Bird'), ('A', 'Amphibian')], max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(choices=[('M', 'Mountain'), ('F', 'Freshwater'), ('W', 'Wetlands'), ('FO', 'Forest'), ('D', 'Desert'), ('S', 'Sea'), ('SA', 'Savannah'), ('J', 'Jungle')], max_length=100),
        ),
    ]
