# Generated by Django 3.1.6 on 2021-04-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0003_auto_20210407_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='NSS',
            field=models.IntegerField(),
        ),
    ]
