# Generated by Django 3.1.6 on 2021-04-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0005_auto_20210407_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representant', models.CharField(max_length=20)),
                ('number_of_visitors', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GroupOfVisitors',
        ),
        migrations.AlterField(
            model_name='animal',
            name='alimentation',
            field=models.CharField(choices=[('C', 'Carnivorous'), ('H', 'Herbivorous'), ('O', 'Omnivorous'), ('F', 'Fruitarian'), ('I', 'Filter'), ('S', 'Scavenger'), ('I', 'Insectivorous'), ('P', 'Piscivorous')], max_length=2),
        ),
        migrations.AlterField(
            model_name='animal',
            name='classes',
            field=models.CharField(choices=[('M', 'Mammal'), ('R', 'Reptile'), ('B', 'Bird'), ('A', 'Amphibian')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZooWeb.sector'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(choices=[('M', 'Mountain'), ('F', 'Freshwater'), ('W', 'Wetlands'), ('FO', 'Forest'), ('D', 'Desert'), ('S', 'Sea'), ('SA', 'Savannah'), ('J', 'Jungle')], max_length=2),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
