# Generated by Django 3.1.6 on 2021-04-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0006_auto_20210407_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(choices=[('Mountain', 'Mountain'), ('Freshwater', 'Freshwater'), ('Wetlands', 'Wetlands'), ('Forest', 'Forest'), ('Desert', 'Desert'), ('Sea', 'Sea'), ('Savannah', 'Savannah'), ('Jungle', 'Jungle')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='animals',
            field=models.ManyToManyField(default=None, to='ZooWeb.Animal'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sectors',
            field=models.ManyToManyField(default=None, to='ZooWeb.Sector'),
        ),
    ]
