# Generated by Django 3.1.6 on 2021-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0006_auto_20210407_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='surname',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
