# Generated by Django 3.1.6 on 2021-04-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0008_auto_20210407_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='alimentation',
            field=models.CharField(choices=[('Carnivorous', 'Carnivorous'), ('Herbivorous', 'Herbivorous'), ('Omnivorous', 'Omnivorous'), ('Fruitarian', 'Fruitarian'), ('Filter', 'Filter'), ('Scavenger', 'Scavenger'), ('Insectivorous', 'Insectivorous'), ('Piscivorous', 'Piscivorous')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='classes',
            field=models.CharField(choices=[('Mammal', 'Mammal'), ('Reptile', 'Reptile'), ('Bird', 'Bird'), ('Amphibian', 'Amphibian')], max_length=20),
        ),
    ]
