# Generated by Django 3.1.6 on 2021-05-05 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0009_auto_20210408_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidedtour',
            name='date',
        ),
        migrations.RemoveField(
            model_name='guidedtour',
            name='sector',
        ),
        migrations.AddField(
            model_name='groupofvisitor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupofvisitor',
            name='sector',
            field=models.ManyToManyField(to='ZooWeb.Sector'),
        ),
    ]
