# Generated by Django 3.1.6 on 2021-05-05 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ZooWeb', '0015_auto_20210505_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofvisitor',
            name='hour',
            field=models.CharField(choices=[('10:00', '10:00'), ('13:00', '13:00'), ('16:00', '16:00'), ('19:00', '19:00')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupofvisitor',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
